name: Formatter Dispatch
on: [workflow_dispatch]

env:
  FLUTTER_CHANNEL: 'stable'
  FLUTTER_VERSION: '3.13.9'
  
jobs:
  format:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          # token: ${{ secrets.VIETMAP_SECRET_TOKEN }}
      - name: format
        run: |
          dart format .
          git config --global user.name "Format Bot"
          git config --global user.email "format-bot-vietmap-flutter-navigation@localhost"
          git add .
          git commit -m "format: ${{ github.event.commits[0].id }}"
          git push
          
